{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zyvor-fleet.name" . }}
  labels:
    {{- include "zyvor-fleet.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "admin.password is required when existingSecret is empty" .Values.admin.password | quote }}
  session-secret: {{ required "sessionSecret is required when existingSecret is empty" .Values.sessionSecret | quote }}
  {{- if .Values.agent.enabled }}
  enrollment-token: {{ required "agent.enrollmentToken is required when agent.enabled=true" .Values.agent.enrollmentToken | quote }}
  {{- end }}
{{- end }}
