apiVersion: v1
kind: Service
metadata:
  name: {{ include "zyvor-fleet.name" . }}
  labels:
    {{- include "zyvor-fleet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "zyvor-fleet.labels" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
